import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../../globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import AuthProvider from '@/lib/SessionProvider'
import { ContextProvider } from '@/context/Customhook'
import { Toaster } from '@/components/ui/sonner'
import Navbar from '@/components/Header'
import { DashboardSideBar } from '@/components/Sidebar/LeftSideBar'
import Container from '@/components/Globals/Container'
import { accessDashboardByUsername } from '@/lib/auth-service'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children, params
}: {
    children: React.ReactNode,
    params: {
        username: string
    }
}) {

    const res = await accessDashboardByUsername(params.username)
    if (!res || !res.success || !res.user) redirect("/")

    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    forcedTheme="dark"
                    storageKey="gamie-theme"
                >
                    <AuthProvider>
                        <ContextProvider >
                            <div>
                                <Navbar isDashboard={true} userData={res.user} />
                                <div className='flex h-full pt-16'>
                                    <DashboardSideBar username={res.user.username} />
                                    <Container>
                                        {children}
                                    </Container>
                                </div>
                                <Toaster position='bottom-center' />
                            </div>
                        </ContextProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
