import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import AuthProvider from '@/lib/SessionProvider'
import { ContextProvider } from '@/context/Customhook'
import { Suspense } from 'react'
import { Toaster } from '@/components/ui/sonner'
import Navbar from '@/components/Header'
import { LeftSideBar, SidebarSkeleton } from '@/components/Sidebar/LeftSideBar'
import Container from '@/components/Globals/Container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="gamie-theme"
        >
          <AuthProvider>
            <ContextProvider >
              <main>
                <Navbar isDashboard={false} />
                <div className='flex h-full pt-16'>
                  <Suspense fallback={<SidebarSkeleton />} >
                    <LeftSideBar />
                  </Suspense>
                  <Container>
                    {children}
                  </Container>
                </div>
                <Toaster position='bottom-center' />
              </main>
            </ContextProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
